# Generated by Django 5.0.7 on 2024-07-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='할일 제목')),
                ('description', models.TextField(max_length=300, verbose_name='할일 세부사항')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='생성 날짜')),
                ('date_deadline', models.DateField(verbose_name='언제까지?')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료여부')),
            ],
        ),
    ]
